# Generated by Django 2.2.9 on 2020-11-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201130_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='grour',
            new_name='group',
        ),
    ]
